"""Add ATS tables

Revision ID: 202cdc3b6dfe
Revises:
Create Date: 2026-03-22 10:55:55.412223

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "202cdc3b6dfe"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_description",
        sa.Column("position", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "application",
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("relevance_score", sa.DECIMAL(precision=1, scale=1), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("resume", mysql.LONGBLOB(), nullable=False),
        sa.Column("resume_file_type", sa.String(length=100), nullable=False),
        sa.Column("resume_file_name", sa.String(length=100), nullable=False),
        sa.Column("processing_status", sa.String(length=100), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_description.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("application")
    op.drop_table("job_description")
    # ### end Alembic commands ###
