"""Add ATS tables

Revision ID: 68c35a53663f
Revises: a38597b9b107
Create Date: 2026-03-20 17:49:27.493806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c35a53663f'
down_revision: Union[str, Sequence[str], None] = 'a38597b9b107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('processing_status', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'processing_status')
    # ### end Alembic commands ###
